### ISSUE TITLE
Project team: Community documentation to create

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#1777]
### Summary

I am listing different sub-projects that the core team is planning or currently working on

### What needs to be done?

- [ ] History page #1731 
- [ ] Different workflow used by community members to participate in the project (short videos, illustrations and stories)
- [ ] Entering the project (sub-chapters on the roles and description of what 'contributions' mean, linking to the acknowledgement chapter #1736 
- [ ] Community support and strategy for different sub-projects #1712
- [ ] Community Charter with governance doc
- [ ] Analytics (Motomo vs Plausible) #1748  and #1750 
- [ ] Release schedule and workflow (review and update community handbook)
- [ ] GSoC and GSoD proposals
- [ ] Community metrics (with Ali Humayun in OLS)
- [ ] Community collaboration: organisations and projects that are building on The Turing Way
- [ ] Rework on the landing page (using FAIR CookBook as an example for how we can create a redacted view of the book) - **CW21 Hack day idea** - based on [FAIR cookbook persona-based view](https://fairplus.github.io/cookbook-dev/intro.html)
- [ ] Funding and positions (not currently required but in case we apply for external funding).

### Who can help?

* Currently the core team members are responsible for working on it but the draft will be open for RfC (Request for Comments) when ready.

---

### Updates

* NA

**Comment by Athene-ai** [comment]
I can help

**Comment by malvikasharan** [comment]
hi @Athene-ai, this issue mainly requires collecting information that are dispersed. Can you suggest how you want to help with this issue?

**Comment by Athene-ai** [comment]
Hi Malika!
I can collect the information requested via tailored techniques

Daniela
