### ISSUE TITLE
[WIP] June Newsletter

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#2420]
Creating draft newsletter for June 2022

Tentative release date: June 15 (Wednesday)

**_Feel free to post ongoing events or updates here, to be added to the newsletter_**

## [Tasks before release](https://the-turing-way.netlify.app/community-handbook/newsletters/newsletters-process.html)

- [x] Collect events from past month (since mid-May 2022)
- [x] Review draft on HackMD (send me an email to review [asteele@turing.ac.uk](https://github.com/alan-turing-institute/the-turing-way/pull/asteele@turing.ac.uk))
- [x] Post on Github
- [x] Review PR
- [x] Publish on Tiny Letter
- [x] Promote more broadly on Twitter, Turing Slack

## Template:
💬 : Community News
🪐 : in _The Turing Way_ orbit
📆 : Upcoming events & opportunities

**Comment by aleesteele** [comment]
In the Turing Orbit 🪐 : https://twitter.com/turinginst/status/1529372017329426435?cxt=HHwWhsC-5eXvtbkqAAAA - Featuring the Turing internship network

**Comment by aleesteele** [comment]
📆: https://www.academictransfer.com/en/313138/4turesearchdata-communications-advisor/

**Comment by aleesteele** [comment]
🐦 Promoted on this thread: https://twitter.com/turingway/status/1539227669023301635
