### ISSUE TITLE
Checklist for correcting/editing YouTube transcripts (editor roles assigned)

### ISSUE THREAD

**Issue by malvikasharan** [the-turing-way/the-turing-way#2795]
# Checklist for editors assigned on YouTube channels

- [ ] **Login to your YouTube Account**
- [ ] **Switch to The Turing Way channel**

  - Step 1: **Click your profile icon on the top right of your screen, click Switch Account**
<img width="359" alt="image" src="https://user-images.githubusercontent.com/5370471/201114799-a79c7284-78c6-4865-82f8-df03be871f56.png">

  - Step 2: **Select The Turing Way**
<img width="301" alt="image" src="https://user-images.githubusercontent.com/5370471/201114581-d4f0978a-a122-4294-a551-97176e531147.png">
- [ ] **You will be brought to the 'Chennel Dashboard'** -> click 'transcript in the list provided on the left handside of the screen'
<img width="986" alt="image" src="https://user-images.githubusercontent.com/5370471/201115337-f48b8774-95fa-4733-b46b-d2f24d2eedff.png">

- [ ] **Scroll down to the video that you would like to edit**
<img width="726" alt="image" src="https://user-images.githubusercontent.com/5370471/201115609-a8381c40-574c-485b-bc10-1bf347406ba1.png">

- [ ] **Select 'Edit' in the second option that is 'Published'**
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/5370471/201115804-fbe24638-c791-4942-8b7b-c877a8ad288c.png">

- [ ] **You should have a pop up screen with video on the right side and transcripts on the left**
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/5370471/201116104-747920df-9bdf-494d-8801-356b1788d443.png">

- [ ] **You can skip through to find parts that you want to proofread and correct**
- [ ] **You can break long sentences in the transcript box by pressing enter**, it will show small chunk of text on screen at a time (this synchronises with video automatically by YouTube when the edits are saved and published)
<img width="340" alt="image" src="https://user-images.githubusercontent.com/5370471/201116520-559b9be0-988f-4784-abc2-7672c7c68019.png">

- [ ] **You can select 'Pause While Typing' - it helps me a lot! :)**
<img width="303" alt="image" src="https://user-images.githubusercontent.com/5370471/201116703-d0151905-512b-4cf2-a683-78ede924d82c.png">

- [ ] **When finished, click publish**

<img width="306" alt="image" src="https://user-images.githubusercontent.com/5370471/201116786-da6a332c-17e7-47a2-9657-77ced496ed60.png">

**Comment by penyuan** [comment]
Thank you @malvikasharan for the detailed illustrated instructions!

Unfortunately I ran into a problem at step 2. When I click on The Turing Way, I am faced with a cute primate telling me "Something went wrong" with no further explanation... 🤔

Anything else I can try?
