### ISSUE TITLE
add data repository checklist to RDM

### ISSUE THREAD

**Issue by EstherPlomp** [the-turing-way/the-turing-way#2907]
### Summary

We mention that you should choose a data repository in [Sharing and Archiving](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-sharing.html), but we don't really provide a lot of detail on how you should do this. I don't want to overload this section, because I think it is good as it is. I think a separate checklist can be added (like the general [RDM checklist](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-checklist.html)). 

### What needs to be done?

- [ ] Is this a helpful idea?
- [ ] Should it be a separate section or be listed under the checklist section? 
- [ ] Is the order of the checklist logical?

### Who can help?

Anyone with experience with data repository - or someone that wants to choose one and has no idea where to start.

### Resources to refer: 

https://ardc.edu.au/resource/guide-to-choosing-a-data-repository

---

### What I have so far: 

What is a Data Repository
_Take over definition that is probably already provided elsewhere_

Three types of data repositories: 
* A general purpose service (such as [Zenodo](https://zenodo.org/) or [Open Science Framework](https://osf.io/)), 
* The service of your institution  
* A field or project specific service, for example ...  or [CRAN](https://cran.r-project.org/) for R-Packages)

Data should be submitted to domain or discipline specific, community recognised repository where possible, or to a general purpose or multidisciplinary repository if no suitable discipline specific repository is available. Discipline specific data repositories are likely to have more functionalities for the type of data that you would like to share, as well as community standards that you can adhere to to make the data more FAIR (_link to FAIR principles_). 

The choice of repository can depend on multiple factors: 
* Your discipline
* Type of digital output
* File size
* Policies/requirements from institutions, national policies, funding agencies 
* Access restrictions 

The following questions may help you to identify a suitable Data Repository:
* Is there a disciplinary-specific community recognised data repository I can submit my data to, thereby helping to preserve my data according to recognised standards in my discipline?
* Is the data repository known by the research community? 
 Are other's using the data repository to share their data? Is it listed in Re3data / FAIRsharing?
* Has a data repository been specified by my funder/publisher/institution? 
* What are the file size requirements and limitations?
* What are the costs for data sharing?
* What data formats are allowed? Will it take the data that you want to share?
* Does it provide a persistent identifier, for example a Digital Object Identifier (DOI)?
* Does it provide the right type of access control that suits the sharing conditions of the data? (restricted access/embargo's)
* Is there support available on how to curate the data/metadata?

**Comment by Karvovskaya** [comment]
@EstherPlomp I am trying to brig this all together here https://hackmd.io/@tFGW252nRcSCnRgpdlcByA/HyNzvRxUo/edit

**Comment by EstherPlomp** [comment]
@Karvovskaya I had a look at the text and made some adjustments! Didn't add a lot of text yet though :(

**Comment by EstherPlomp** [comment]
Fixed by #3214
