### ISSUE TITLE
2023 conferences to attend, abstracts to submit / Tell us you are attending an event!

### ISSUE THREAD

**Issue by aleesteele** [the-turing-way/the-turing-way#2941]
Closes #2249 with a 2023 update.

✨ **Attending a conference and interested in meeting The Turing Way community?: Fill out this pad: https://pad.sfconservancy.org/p/ttw-event-calendar-2023** ✨ 

### Summary

Conferences pop up all the time that are of interest to The Turing Way Community. While a number of conferences that  that are open for abstract submissions. Please respond below (or message me on Slack, or email theturingway@gmail.com or asteele@turing.ac.uk) with which conference you would like to attend and represent The Turing Way... or with a conference suggestion of where we should go next! We would love to have folks representing the community in spaces that are important to them, and/or particularly voices in the community that we haven't supported or heard previously. 

For planning, we have an ongoing google sheet to log updates and plan events within the organising team: https://docs.google.com/spreadsheets/d/1C-VZvmFL4PnSBsv_G9ZD3dwjIYLno3NyL7oHvbplnWs/edit#gid=577525947

### Ongoing conference list (taken from #2249)
_Please feel free to edit this issue directly _

#### Open ecosystem/Returning (Attended/Applied in 2022)

- [x] csv,CONF
- [x] RightsCon
- [x] MozFest
- [x] FOSDEM
- [x] Collaborations Workshop
- [ ] RSECon
- [ ] WriteTheDocs
- [ ] CarpentryCon
- [x] FORCE11
- [x] MetaScience 22
- [ ] Big Team Science 23
- [x] AI-UK
- [ ] CodeForAll
- [ ] AllThingsOpen
- [ ] [PUBMET2023](https://pubmet2023.unizd.hr/)

#### Mentorship-oriented programs
- Google Season of Docs - https://developers.google.com/season-of-docs (orgs submit by 3 Feb) - [issues tagged gsod2020](https://github.com/alan-turing-institute/the-turing-way/labels/gsod2020) from @paulowoicho 
- Google Season of Code (#2240 #2266 is from 2022) - https://summerofcode.withgoogle.com/ (orgs submit by 7 Feb)
- Turing Enrichment Scheme - https://www.turing.ac.uk/work-turing/studentships/enrichment (teams submit by 31 Jan)
- Outreachy Programme - https://www.outreachy.org/ (orgs submit by 10 Feb)

#### Computational conferences
_We would love to have more folks present The Turing Way in their own computational communities, so we can learn how to improve the resource for people's specific contexts... Are there ones that we are missing here? These immediately come to mind:_
- useR!
- PyCon
- PyData
- SciPy
- NHS-R

#### Field-specific conferences
_Speaking at a computational biology conference? A sociology conference? A tech ethics conference? A environmental data science conference?_

#### AI/Data Science Oriented conferences
- CHI: https://chi2022.acm.org/
- ACM FaCCT: https://facctconference.org/
- DIS: https://dis.acm.org/2022/

---

### Updates

*

**Comment by EstherPlomp** [comment]
Maybe relevant: 
The **International Open Science Conference** offers insights into both practical and technical innovations that serve the implementation of open practices as well as current and pioneering developments in the global Open Science movement. Such developments are, for example, the increasing plea for open practices as lessons learned from global crises as well as recent discussions on the relation of Open Science, civic science education, and knowledge equity. Furthermore, the conference offers many opportunities for networking and exchange.

https:/www.open-science-conference.eu/calls2023/

**Comment by aleesteele** [comment]
This very much looks like something we should submit to, @EstherPlomp! Should we use the next coworking call to talk about this call for folks, or reserve some space at the next Collab Cafe on 15 Feb?

**Comment by EstherPlomp** [comment]
I have a couple of other things going on today so I won't be joining! (I think you also already had other plans :)) 

another conference that might be interesting - but that I can't attend: Edinburgh Open Research Conference / http://journals.ed.ac.uk/eor/about/submissions

**Comment by aleesteele** [comment]
- FOSSY US: https://2023.fossy.us/
-

**Comment by aleesteele** [comment]
## Archive

### Archiving presentations/events from 2023 so far
- [x] 7 February - Data Science Perspectives (Newcastle UK) - #2952
- [x] 7-8 February - State of Open Con (London, UK) 
- [x] 9 February - Open Data Day / TPS Coffee Chats (online) - no issue
- [x] 10 March - Data Hazards Keynote (in person, London, UK) - no issue 
- [x] 10 March - DHNordicBaltic Conference - no issue
- [x] 14 March - Maintenance as a Turing Way (Berlin, Germany) - #2993 
- [x] 21 March - Researcher to Reader Conference (London) - no issue
- [x] 24 March - RDA Plenary (Stockholm, Sweden)- no issue
- [x] 21-25 March - MozFest (online) -  no issue
- [x] 21-22 March - AI-UK Turing Way exhibit (London, UK) - no issue
- [x] 22 March- Git Good Workshop @ AI-UK (London, UK) - #3006 
- [x] 31 March - Fireside Chat - #2982 
- [x] 13 April - BCSCWomen Lovelace Colloquium (Sheffield, UK) - no issue
- [x] 18-20 April - FORCE 2023 (Online) - no issue 
- [x] 17-19 April - CZI Meeting (Buenos Aires, Argentina)
- [x] 19 April - Climate Informatics Panel (Cambridge, UK, online)
- [x] 19-20 - csv,CONF (Buenos Aires, Argentina)
- [x] 20 April - Julia Silge visit (London, UK)
- [x] 24 April - UCL Open Science and the Case for Social Justice (London, UK)
- [x] 27 April - TTW Case study workshop RSS/UKRM Repro Roundtable (online)
- [x] 2-4 May - Collaborations Workshop (Manchester, UK) - see #collaborations-workshop-23 on slack, two workshops given
- [x] 5 May - Fireside Chat (online)
- [x] 16 May - Edinburgh Open Research Conference 2023 (Edinburgh, UK)
- [x] 17 May - TPS Team Meeting (online)
- [x] 18 May - TPS Coffee Chat (London, UK & online)
- [x] 19 May - EDS Book + Climate Informations "Chat with Experts" (online)
- [x] 25 May - OSPO++ Presentation (online)
- [x] 1 June - Lunch & Learn (internal ATI event) 
- [x] 12-14 - Moving frontiers of the demos (Geneva, CH)
- [x] 19-20 June - Data Justice Conference (Cardiff, UK)
- [x] 21 June - UN OSPOs for Good (NY, USA, hybrid)
- [x] 28 June - ACM-REP (CA, USA, hybrid)
- [x] 27-29 June - Open Science EU (online)
- [x] 3-9 July - London Data Week (London, UK, in person & online)
- [x] 12 July - QQR @ Turing (London, UK, in person)
- [ ] 21 August - Widening Participation Workshop (London, UK, in person)
- [ ] 4 September - OpenFest (Sheffield, UK, online)
- [ ] 21 September - Festival of Hidden REF (Bristol, UK)
- [ ] 25-27 September - Open Science Fair (Madrid, Spain)
- [ ] 26-28 September - deRSE Unconference (Dornburger Schlösser, Jena, Germany)
- [ ] 23-25 October - [Big Team Science](https://bigteamscienceconference.github.io/) (online)
- [ ] 23-29 October - [Open Access Week](https://www.openaccessweek.org/) (online)
- [ ] 8-10 November - Munin Conference on Scholarly Publishing (Tromsø, Norway)

### Archiving team events
- [x] 10 March - Core Team Quarterly Meeting 
- [x] 29 March - Infrastructure Meeting - organised in #2690 

### Archiving applications submitted
- [x] FOSDEM (accepted) 
- [x] Metascience 2023 (rejected)
- [x] RightsCon (rejected)
- [x] Data Justice 2023 (accepted)
- [x] FOSS Backstage (accepted)
- [x] FORCE11 (accepted)
- [x] MozFest 2023 (accepted)
- [x] Collaborations Workshop (accepted)
- [x] Edinburgh Open Research Conference (accepted)
- [x] Open Research EU (accepted)
- [x] Open Science Fair (accepted)

### Invited talks
- [x] UCL Talk
- [x] Climate informatics
- [x] OSPO++
- [x] HiddenREF Festival
- [ ] NHS-R Community (Birmingham, UK, 17-18 Oct)

### Themed weeks
- Open Data Day:
- Open Access Week: October 23 - 29, 2023: https://www.openaccessweek.org/
- Big Team Science: 23-25 October: bigteamscienceconference.github.io/
