### ISSUE TITLE
Individual Checklist/Template ideas

### ISSUE THREAD

**Issue by annakrystalli** [the-turing-way/the-turing-way#67]
In this issue, we can compile a list of useful individual checklists/templates:

### Checklists

- [ ] Group member onboarding checklist
- [ ] Group member offboarding checklist
- [ ] Project owner checklist
- [ ] Supervisor checklist
- [ ] Administrator (funder) checklist

### Templates

- [ ] Research Compendium Repository README template
